{{- $root := . -}}
{{- $defaultGatewayEnv := dict "ORCHESTRATOR_URL" (printf "http://%s-orchestrator:%d" (include "oss-ai-agent-tool.fullname" $root) ($root.Values.orchestrator.service.port | default 4000)) "INDEXER_URL" (printf "http://%s-indexer:%d" (include "oss-ai-agent-tool.fullname" $root) ($root.Values.indexer.service.port | default 7070)) -}}
{{- $gatewayEnv := merge $defaultGatewayEnv ($root.Values.gatewayApi.env | default dict) -}}
{{- if and .Values.gatewayApi.tls.enabled (not .Values.gatewayApi.tls.secretName) -}}
  {{- fail "gatewayApi.tls.secretName must be provided when gatewayApi.tls.enabled is true" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-gateway-api
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gatewayApi.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway-api
  template:
    metadata:
      labels:
        {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway-api
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gateway-api
          image: {{ include "oss-ai-agent-tool.image" (dict "Values" .Values "Chart" .Chart "component" "gateway-api") }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.gatewayApi.containerPort | default 8080 }}
          env:
            - name: PORT
              value: {{ (.Values.gatewayApi.containerPort | default 8080) | quote }}
          {{- range $key, $value := $gatewayEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.gatewayApi.tls.enabled }}
            {{- $mountPath := .Values.gatewayApi.tls.mountPath | default "/etc/orchestrator/tls" -}}
            {{- $clientCertFile := .Values.gatewayApi.tls.clientCertFile | default "client.crt" -}}
            {{- $clientKeyFile := .Values.gatewayApi.tls.clientKeyFile | default "client.key" -}}
            {{- $caFile := .Values.gatewayApi.tls.caFile | default "ca.crt" -}}
            - name: ORCHESTRATOR_TLS_ENABLED
              value: "true"
            - name: ORCHESTRATOR_CLIENT_CERT
              value: {{ printf "%s/%s" $mountPath $clientCertFile | quote }}
            - name: ORCHESTRATOR_CLIENT_KEY
              value: {{ printf "%s/%s" $mountPath $clientKeyFile | quote }}
            {{- if $caFile }}
            - name: ORCHESTRATOR_CA_CERT
              value: {{ printf "%s/%s" $mountPath $caFile | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.gatewayApi.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.gatewayApi.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.gatewayApi.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- else }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          {{- end }}
          {{- with .Values.gatewayApi.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- else }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          {{- end }}
          {{- if .Values.gatewayApi.tls.enabled }}
          volumeMounts:
            - name: orchestrator-client-tls
              mountPath: {{ (.Values.gatewayApi.tls.mountPath | default "/etc/orchestrator/tls") | quote }}
              readOnly: true
          {{- end }}
      {{- if .Values.gatewayApi.tls.enabled }}
      volumes:
        - name: orchestrator-client-tls
          secret:
            secretName: {{ .Values.gatewayApi.tls.secretName | quote }}
      {{- end }}
