apiVersion: v1
kind: Service
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-gateway-api
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-api
  ports:
    - name: http
      port: 80
      targetPort: http
