{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-jaeger
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
  ports:
    - name: http
      port: 16686
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-jaeger
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: jaeger
  template:
    metadata:
      labels:
        {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: jaeger
    spec:
      containers:
        - name: jaeger
          image: {{ .Values.jaeger.image | default "jaegertracing/all-in-one:1.57" }}
          imagePullPolicy: IfNotPresent
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
          {{- with .Values.jaeger.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
