{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-default
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector: {}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  egress:
    - {}
  {{- end }}
{{- end }}
