{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-postgres
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-postgres
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "oss-ai-agent-tool.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "oss-ai-agent-tool.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | default "postgres:15-alpine" }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | default "ossaat" | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | default "ossaat" | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "oss-ai-agent-tool.fullname" . }}-postgres
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "oss-ai-agent-tool.fullname" . }}-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-postgres
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | default "8Gi" }}
  {{- with .Values.postgres.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oss-ai-agent-tool.fullname" . }}-postgres
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (.Values.postgres.password | default "ossaat") | b64enc }}
{{- end }}
