image:
  repo: ghcr.io/yourorg/oss-ai-agent-tool
  tag: "0.1.0"
  pullPolicy: IfNotPresent

runMode: consumer            # or enterprise

messaging:
  type: rabbitmq             # or kafka

gatewayApi:
  replicas: 2
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "500m", memory: "256Mi" }

orchestrator:
  replicas: 2
  env:
    OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT: "false"
    RABBITMQ_USERNAME: guest
    RABBITMQ_PASSWORD: guest
    RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    RABBITMQ_PREFETCH: "8"
    RABBITMQ_RETRY_DELAY_MS: "1000"
  hpa:
    min: 2
    max: 10
    targetQueueDepth: 5

redis:
  enabled: true
postgres:
  enabled: true
rabbitmq:
  enabled: true
  host: rabbitmq
  port: 5672
  username: guest
  passwordSecretName: ""
  passwordSecretKey: password
kafka:
  enabled: false

jaeger:
  enabled: true
langfuse:
  enabled: true

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
          service: gateway
  tls: []
