blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/OSS-AI-Agent-Tool/OSS-AI-Agent-Tool/security/advisories/new
    about: Please use the private security advisory form for vulnerabilities.

